# Generated by Django 3.0.4 on 2020-11-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='head_man',
            field=models.CharField(default='', max_length=256),
        ),
    ]
