# Generated by Django 3.0.4 on 2020-11-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_plan_head_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='group_link',
            field=models.URLField(default=''),
        ),
    ]
