# Generated by Django 3.1.2 on 2020-11-17 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0003_auto_20201117_0042'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0003_plan_group_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='participation.club', verbose_name='باشگاه'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.CharField(default='', max_length=256, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='destination_address',
            field=models.CharField(default='', max_length=256, verbose_name='ادرس مقصد'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='group_link',
            field=models.URLField(default='', verbose_name='لینک گروه'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='head_man',
            field=models.CharField(default='', max_length=256, verbose_name='سرپرست'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='زمان و تاریخ شروع'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='planparticipant',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.plan', verbose_name='برنامه'),
        ),
        migrations.AlterField(
            model_name='planparticipant',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=255, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='planparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
