# Generated by Django 3.1.4 on 2020-12-08 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0004_auto_20201208_1040'),
        ('planning', '0004_auto_20201117_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='participation.club', verbose_name='club'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.CharField(default='', max_length=256, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='destination_address',
            field=models.CharField(default='', max_length=256, verbose_name='destination_address'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='group_link',
            field=models.URLField(default='', verbose_name='group_link'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='head_man',
            field=models.CharField(default='', max_length=256, verbose_name='head_man'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='start_datetime'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='planparticipant',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.plan', verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='planparticipant',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=255, verbose_name='status'),
        ),
    ]
