# Generated by Django 3.1.3 on 2020-12-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_auto_20201208_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='planparticipant',
            name='duty',
            field=models.CharField(max_length=1000, null=True, verbose_name='duty'),
        ),
    ]
