# Generated by Django 3.1.2 on 2020-12-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_planparticipant_isdutyseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='planparticipant',
            name='role',
            field=models.CharField(max_length=40, null=True, verbose_name='role'),
        ),
    ]
