# Generated by Django 3.1.3 on 2020-12-26 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0004_auto_20201208_1040'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0008_planparticipant_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='title')),
                ('description', models.CharField(default='', max_length=256, verbose_name='description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='amount')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='participation.club', verbose_name='club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
