# Generated by Django 3.1.3 on 2020-12-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='planning.plan', verbose_name='club'),
        ),
    ]
