# Generated by Django 3.1.4 on 2021-01-05 09:51

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_plan_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='report',
            field=markdownx.models.MarkdownxField(default=''),
        ),
    ]
