# Generated by Django 3.1.4 on 2021-01-05 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0013_auto_20210105_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='title')),
                ('description', models.CharField(default='', max_length=256, verbose_name='description')),
                ('time', models.DateTimeField(verbose_name='time')),
                ('isSeen', models.BooleanField(default=False, verbose_name='isSeen')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.plan', verbose_name='plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
