# Generated by Django 3.1.4 on 2021-01-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0014_plannotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannotification',
            name='isSeen',
            field=models.IntegerField(default=2, verbose_name='isSeen'),
        ),
    ]
