# Generated by Django 3.1.2 on 2021-02-19 10:18

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('planning', '0019_auto_20210219_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='report',
            field=markdownx.models.MarkdownxField(default=''),
        ),
    ]
