# Generated by Django 3.1.4 on 2020-12-08 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('participation', '0003_auto_20201117_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='club',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participation.club', verbose_name='club'),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='pending',
            field=models.BooleanField(default=True, verbose_name='pending'),
        ),
    ]
